services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: station_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - station-net

  backend:
    image: ghcr.io/mohamediliasskaddar/backend-app:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/station_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - station-net

  frontend:
    image: ghcr.io/mohamediliasskaddar/frontend-app:latest
    restart: always
    depends_on:
      - backend
    networks:
      - station-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - station-net

volumes:
  pgdata:

networks:
  station-net: