services:

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: station_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - station-net

  backend:
    build: ./gestion-station
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - station-net

  frontend:
    build: ./gestion-station-web
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - station-net

volumes:
  pgdata:

networks:
  station-net: