#spring.application.name=gestion-station

spring:
  application:
      name: gestion-station
  datasource:
    url: jdbc:postgresql://localhost:5432/station_db
#    url: jdbc:postgresql://db:5432/station_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect