- name: Setup EC2
  hosts: web
  become: yes

  tasks:
    - name: Enable passwordless sudo
      lineinfile:
          path: /etc/sudoers
          line: "ubuntu ALL=(ALL) NOPASSWD:ALL"
          validate: 'visudo -cf %s'
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes