name: Frontend CI

on:
  push:
    branches:
      - master
    paths:
      - 'gestion-station-web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gestion-station-web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build

      - name: Build Docker image
        run: |
          docker build -t frontend-app ./gestion-station-web